spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    consumer:
      group-id: auth-service-group
    bootstrap-server:
      server:
        port: localhost:9092

jwt:
  secret:
    access: ENNBmE4TlxtYExaNse02RTIexWHOPxdSAq3RkAQJRhNwrAqbxbynXVpOiN6GnalGyNPS6dLj7nyr8qCoXgRBSD
    refresh: ${jwt.refresh-expiration-ms}
  expiration-ms: ${jwt.expiration-ms}
  refresh-expiration-ms: ${jwt.refresh-expiration-ms}

kafka:
  topics:
    google-refresh-token: "google.refresh.token"